<?
echo $this->theme .'風格';
echo $this->headLink()
		->setStylesheet($this->baseUrl().'/css/ui.jqgrid.css')
		->setStylesheet($this->baseUrl().'/css/'.$this->theme.'/jquery.ui.theme.css')
		->setStylesheet($this->baseUrl().'/css/'.$this->theme.'/jquery-ui.css')
		->setStylesheet($this->baseUrl().'/css/'.$this->theme.'/jquery-ui.min.css');


?>

<script src="<?echo $this->baseUrl();?>/js/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/grid.locale-zh_tw.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery.jqGrid.min.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/dtable.js" type="text/javascript"></script>

<?
echo $this->user->user_id . ":";
echo $this->user->cname;
echo $this->user->role;
?>
<div id="MasterDetail" style="overflow:scroll; width:900px; height:400px;">
	<table id="MasterGrid0" join type="edit,add,del,search" sql="editgrid" db="toyota" 
		table="system" value= "系統組態設定" 
		title="代號,組態名稱,圖片位址,HTML描述,型態" 
		field="system_id,name,imgurl,description,mytype" 
		key="system_id" >
	</table>
	<div id="mpager0"></div>
<hr />
<!--
<table id="listTable" type="edit" sql="editgrid" db="toyota" table="user" value= "帳號管理" name="代號,帳號,姓名,角色" field="user_id,name,cname,role" key="user_id" where= "user_id='<?//echo $this->user->user_id?>'"></table>
-->
<span id="spaMsg"></span>
<br />

</div>
