<?
echo $this->headLink()
			->setStylesheet($this->baseUrl().'/css/ui.jqgrid.css');
?>
<script src="<?echo $this->baseUrl();?>/js/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/grid.locale-zh_tw.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery.jqGrid.min.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/dtable.js" type="text/javascript"></script>
<div id="MasterDetail" style="overflow:scroll; width:100%; height:100%;">
	<table id="MasterGrid0" join type="search" sql="editgrid" db="toyota" 
		table="portfolioscore" value= "訓考歷程" 
		title="任務代號,任務名稱,考卷代號,員工代號,部門,第幾次考試,考試類型,成績" 
		field="task_id,task_name,exampaper_id,user_id,department,exampaper,partition,sumscore" 
		key="exampaper_id" where= "user_id='<?echo $this->user->user_id?>'">
	</table>
	<div id="mpager0"></div>

<!--
<table id="listTable" type="edit" sql="editgrid" db="toyota" table="user" value= "帳號管理" name="代號,帳號,姓名,角色" field="user_id,name,cname,role" key="user_id" where= "user_id='<?//echo $this->user->user_id?>'"></table>
-->
<!--
,紀錄查詢開放時間
,exampaper_searchrecord
-->
<hr />
<span id="spaMsg"></span>
<br />
</div>

