<?
// for inner tags using 'Value' placement
echo $this->headLink()
		->setStylesheet($this->baseUrl().'/css/ui.jqgrid.css')
		->setStylesheet($this->baseUrl().'/css/'.$this->theme.'/jquery.ui.theme.css')
		->setStylesheet($this->baseUrl().'/css/'.$this->theme.'/jquery-ui.css')
		->setStylesheet($this->baseUrl().'/css/'.$this->theme.'/jquery-ui.min.css');


?>
<script src="<?echo $this->baseUrl();?>/js/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/grid.locale-zh_tw.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery.jqGrid.min.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/dtable.js" type="text/javascript"></script>

<?
$this->form->addElement('select','exampaper_id', 
	array(
	'decorators' => $this->form->genericDecorators,
	'label' => '考卷名稱',
	'value' => '',
	'class' => 'idatabase ' . ACTIVE_STYLE,
	'type' 	=> 'select',
	'sql'	=> 'select',
	'db'	=> 'toyota',
	'table'	=> 'examall',
	'field'	=> 'ep_name,exampaper_id',
	'name'	=> 'exampaper_id',
	'key'	=> 'user_id',
	'pk'	=> $this->user->user_id,
	'multiOptions' => array(
				'1'    => '請選擇',
			),
));

$this->form->addElement('submit', 'formsubmit', 
	array(
	'decorators' => $this->form->simpleDecorators,
	'class' => ACTIVE_STYLE,	
	'label'       => '查詢',
));

//圖形型態  barVertGrouped
$exampaperid = $this->exampaper_id;
echo $this->Chart('r','南都汽車成績分析','toyota','exampart','分類,最大,最小,平均','name,maxscore,minscore,avgscore',"user_id = '$userid' and exampaper_id = '$exampaperid'");
//echo "===> $userid' and exampaper_id = '$exampaperid'";
?>
<div id="MasterDetail" style="overflow-y: auto;overflow-x: hidden; width:100%; height:100%;">
	<table id="MasterGrid0" join type="edit,add,copy,del,search" sql="editgrid" db="toyota" 
		table="user" value= "使用者管理" 
		title="代號,帳號,姓名,角色,主管" 
		field="user_id,name,cname,role,supervisor" 
		key="user_id" >
	</table>
<div id="mpager0"></div>

<div id="view-content">
	<?php echo $this->form->setAction($this->url()) . '<br>';?>
</div>
<div id="masterDetail" style="overflow:scroll; width:800px; height:400px;">
<? if ($this->exampaper_id =='') :?>
<?else: ?>
<div id="gChart" class="chart" style="width: auto; height: 380px;"></div>
<div id="qrCode" style="width: 45px; height: 30px;"></div>
<?endif ?>
</div>
</div> 

</div>
<hr />
<span id="spaMsg" class="<?echo ERROR_STYLE;?>" title="<?echo $this->module . '/' . $this->controller . '/' . $this->action;?>">
<?echo $this->status;?>
</span>




<!--C:\AppServ\www\cca\application\modules\campaign\views\scripts\campaign\listcampaign.phtml
-->







