
<?
echo $this->headLink()
		->setStylesheet($this->baseUrl().'/css/ui.jqgrid.css')
		->setStylesheet($this->baseUrl().'/css/'.$this->theme.'/jquery.ui.theme.css')
		->setStylesheet($this->baseUrl().'/css/'.$this->theme.'/jquery-ui.css')
		->setStylesheet($this->baseUrl().'/css/'.$this->theme.'/jquery-ui.min.css');


?>
<script src="<?echo $this->baseUrl();?>/js/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/grid.locale-zh_tw.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery.jqGrid.min.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/dtable.js" type="text/javascript"></script>

<div id="MasterDetail" style="overflow-y: auto;overflow-x: hidden; width:100%; height:100%;">
	<table id="MasterGrid0" join type="edit,add,copy,del,search" sql="editgrid" db="toyota" 
		table="user" value= "使用者管理" 
		title="代號,帳號,姓名,角色,主管" 
		field="user_id,name,cname,role,supervisor" 
		key="user_id" >
	</table>
<div id="mpager0"></div>
<div id="gtw" style="margin-left:10px" class="database <?echo STYLE;?>" type="gtw" sql="select" db="toyota" table="department,user" field="supervisor,name" key="department_id">
</div> 
</div>
<hr />
<span id="spaMsg" class="<?echo ERROR_STYLE;?>" title="<?echo $this->module . '/' . $this->controller . '/' . $this->action;?>">
<?echo $this->status;?>
</span>

<!--
<div id="JQTreeview" class="database" type="auto" sql="select" db="toyota" table="user,user" field="name,role" key="user_id" where="1=1">
</div> 
-->

	 