<?
echo $this->headLink()
			->setStylesheet($this->baseUrl().'/css/ui.jqgrid.css');
?>
<script src="<?echo $this->baseUrl();?>/js/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/grid.locale-zh_tw.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery.jqGrid.min.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/dtable.js" type="text/javascript"></script>
<div id="MasterDetail" style="overflow-y: auto;overflow-x: hidden; width:100%; height:96%;">
	<table id="MasterGrid0" join type="edit,add,del,search" sql="editgrid" db="toyota" 
		table="examinfo" value= "考試活動設定" 
		title="考卷編號,已存在的考卷" 
		field="examinfo_id,exampaper_name" 
		key="examinfo_id">
	</table>
	<div id="mpager0"></div>
<!--
<table id="listTable" type="edit" sql="editgrid" db="toyota" table="user" value= "帳號管理" name="代號,帳號,姓名,角色" field="user_id,name,cname,role" key="user_id" where= "user_id='<?//echo $this->user->user_id?>'"></table>
-->
<hr />
<br />
<input type="button"  value="新增考試活動" class="ui-state-default"  onclick= "window.location.href='<?echo $this->baseUrl();?>/exam/exam/step1'"/>
</div>
<span id="spaMsg" class="<?echo ERROR_STYLE;?>" title="<?echo $this->module . '/' . $this->controller . '/' . $this->action;?>">
	<?echo $this->status;?>
</span>
