<?
echo $this->headLink()
			->setStylesheet($this->baseUrl().'/css/ui.jqgrid.css');
?>
<script src="<?echo $this->baseUrl();?>/js/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/grid.locale-zh_tw.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery.jqGrid.min.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/dtable.js" type="text/javascript"></script>

<?
$this->form->addElement('select','exam_id', 
	array(
	'decorators' => $this->form->genericDecorators,
	'label' => '考試名稱',
	'value' => '',
	'class' => 'idatabase',
	'type' 	=> 'select',
	'sql'	=> 'select',
	'db'	=> 'toyota',
	'table'	=> 'exam',
	'field'	=> 'name,exam_id',
	'name'	=> 'exam_id',
	//'key'	=> 'user_id',
	//'pk'	=> $this->user->user_id,
	'multiOptions' => array(
				'1'    => '請選擇',
			),
));
$this->form->addElement('submit', 'formsubmit', 
	array(
	'decorators' => $this->form->simpleDecorators,
	'label'       => '結束考試',
));
?>
<div id="view-content">
	<?php
	echo $this->form->setAction($this->baseUrl().
	'/exam/exam/monitor') . '<br>';
	?>
</div>
<div id="MasterDetail" style="overflow-y: auto;overflow-x: hidden; width:100%; height:85%;">
	<table id="MasterGrid0" join type="edit,add,del,search" sql="editgrid" db="toyota" 
		table="exampaper" value= "考卷交還設定(將4更改為3)" 
		title="代號,考生,考卷別,考試名稱,考卷狀態" 
		field="exampaper_id,user_id,name,exam_id,mark" 
		key="exampaper_id"
		where= "exam_id='<?echo $this->exam_id;?>'"	>
	</table>
	<div id="mpager0"></div>

<!--
<table id="listTable" type="edit" sql="editgrid" db="toyota" table="user" value= "帳號管理" name="代號,帳號,姓名,角色" field="user_id,name,cname,role" key="user_id" where= "user_id='<?//echo $this->user->user_id?>'"></table>
-->
<hr />
</div>
<span id="spaMsg" class="<?echo ERROR_STYLE;?>" title="<?echo $this->module . '/' . $this->controller . '/' . $this->action;?>">
<?echo $this->status;?>
</span>