<?
echo $this->headLink()
			->setStylesheet($this->baseUrl().'/css/ui.jqgrid.css');
?>
<script src="<?echo $this->baseUrl();?>/js/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/grid.locale-zh_tw.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery.jqGrid.min.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/dtable.js" type="text/javascript"></script>
<img src="<?echo $this->baseUrl();?>/images/step4.jpg">
<div id="MasterDetail" style="overflow:scroll; width:100%; height:100%;">
	<table id="MasterGrid0" join type="add,del,search" sql="editgrid" db="toyota" 
		table="user" value= "新增測驗Step4" 
		title="編號,考生" 
		field="user_id,name" key="user_id" >
	</table>
	<div id="mpager0"></div>
<hr />
<!--
<table id="listTable" type="edit" sql="editgrid" db="toyota" table="user" value= "帳號管理" name="代號,帳號,姓名,角色" field="user_id,name,cname,role" key="user_id" where= "user_id='<?//echo $this->user->user_id?>'"></table>
-->
<span id="spaMsg"></span>
<br />
<input type="button"  value="上一步" class="<?echo STYLE;?>"  onclick= "window.location.href='<?echo $this->baseUrl();?>/exam/exam/step3'">
<input type="button"  value="完成" class="u<?echo STYLE;?>"  onclick= "window.location.href='<?echo $this->baseUrl();?>/exam/exam/addexam'">
</div>