<?
echo $this->headLink()
			->setStylesheet($this->baseUrl().'/css/ui.jqgrid.css')
			->setStylesheet($this->baseUrl().'/css/themes/pepper-grinder/jquery.ui.theme.css');	
?>
<script src="<?echo $this->baseUrl();?>/js/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/grid.locale-zh_tw.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery.jqGrid.min.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/dtable.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/masterdetail.js" type="text/javascript"></script>

<div id="tree1"></div>
<script>
$(document).ready(function() { 
		
var data = [
    {
        label: '<div id="div_1"><input id="selectall_1" type="checkbox" onclick="setSelectall(this);"/>Á`¸g²z',
        children: [
            { label: '<label id="1" for=checkbox_1><input id=checkbox_1 type="checkbox" />³¯©v»¨</label>' },
            { label: '<label id="2" for=checkbox_2><input id=checkbox_2 type="checkbox" />¤ý¸t½å</label></div>' }
        ]
    },
    {
        label: '<div id="div_2"><input id="selectall_2" type="checkbox"  onclick="setSelectall(this);" />¸­¨}´Ó',
        children: [
            { label: '<label id="3" for=checkbox_3><input type="checkbox" />§õºa®x</label></div>' }
        ]
    }
];

		$('#tree1').tree({
			data: data,
			dragAndDrop: true,
			autoOpen: 0,
			autoEscape: false,
			selectable: true,
			onCanSelectNode: function(node) {
				if (node.children.length == 0) {
					//alert("Nodes without children can be selected");
					return true;
				} else {
					g = node.children("input");
					alert("g number:"+g.attr("id"));
					//alert("Nodes with children cannot be selected");
					return false;
				}
			}
		});
});
</script>