<?
echo $this->headLink()
		->setStylesheet($this->baseUrl().'/css/ui.jqgrid.css')
		->setStylesheet($this->baseUrl().'/css/'.$this->theme.'/jquery.ui.theme.css')
		->setStylesheet($this->baseUrl().'/css/'.$this->theme.'/jquery-ui.css')
		->setStylesheet($this->baseUrl().'/css/'.$this->theme.'/jquery-ui.min.css');


?>

<script src="<?echo $this->baseUrl();?>/js/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/grid.locale-zh_tw.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery.jqGrid.min.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/dtable.js" type="text/javascript"></script>
<?
$this->form->addElement('select','exam_id', 
	array(
	'decorators' => $this->form->genericDecorators,
	'label' => '群組名稱',
	'value' => '',
	'class' => 'idatabase ' . STYLE,
	'type' 	=> 'select',
	'sql'	=> 'select',
	'db'	=> 'toyota',
	'table'	=> 'group',
	'field'	=> 'name,group_id',
	'name'	=> 'group_id',
	//'key'	=> 'user_id',
	//'pk'	=> $this->user->user_id,
	'multiOptions' => array(
				'1'    => '請選擇',
			),
));
$this->form->addElement('submit', 'formsubmit', 
	array(
	'decorators' => $this->form->simpleDecorators,
	'label'       => '確定',
));
?>
<div id="view-content">
	<?php
	echo $this->form->setAction($this->baseUrl().'/exam/user/groupuser') . '<br>';
	?>
</div>
<div id="MasterDetail" style="overflow-y: auto;overflow-x: hidden; width:100%; height:82%;">
	<table id="MasterGrid0" join="2" type="edit,add,del,search" sql="editgrid" db="toyota"
		 table="group" value= "群組管理" 
		 title="群組代號,群組名稱" 
		 field="group_id,name" 
		 key="group_id" >
	</table>
	<div id="mpager0"></div>
<hr />

<table id="DetailGrid0" type="edit,add,del,search" sql="editgrid" db="toyota"
 table="role" value= "群組管理" 
 title="角色代號,角色名稱,群組代號" 
 field="role_id,name,group_id" 
 key="group_id" ></table>
<div id="dpager0"></div>
</div>
<hr />
<span id="spaMsg" class="<?echo ERROR_STYLE;?>" title="<?echo $this->module . '/' . $this->controller . '/' . $this->action;?>">
<?echo $this->status;?>
</span>
