<?
echo $this->headLink()
		->setStylesheet($this->baseUrl().'/css/ui.jqgrid.css')
		->setStylesheet($this->baseUrl().'/css/'.$this->theme.'/jquery.ui.theme.css')
		->setStylesheet($this->baseUrl().'/css/'.$this->theme.'/jquery-ui.css')
		->setStylesheet($this->baseUrl().'/css/'.$this->theme.'/jquery-ui.min.css');


?>
<script src="<?echo $this->baseUrl();?>/js/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/grid.locale-zh_tw.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery.jqGrid.min.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/dtable.js" type="text/javascript"></script>
<div id="MasterDetail" style="overflow:scroll; width:100%; height:100%;">
	<table id="MasterGrid0" join type="edit,add,del,search" sql="editgrid" db="toyota" 
		table="user" value= "帳號管理" 
		title="帳號,姓名,中文全名,角色" 
		field="user_id,name,cname,role" 
		key="user_id"
		where= "user_id='<?echo $this->user->user_id?>'">
	</table>
	<div id="mpager0"></div>
<hr />
</div>
<!--
field="User_id,name,cname,role" ==>首字大寫表示不可編輯
<table id="listTable" type="edit,add,copy,del,search" sql="editgrid" db="toyota" table="questions" value= "考卷管理" name="考卷代號,考試名稱,題庫代號,題目代號,題型代號" field="questions_id,name,exampaper_id,question_id,type" key="questions_id" ></table>
<table id="listTable" type="edit" sql="editgrid" db="toyota" table="user" value= "帳號管理" name="代號,帳號,姓名,角色" field="user_id,name,cname,role" key="user_id" where= "user_id='<?//echo $this->user->user_id?>'"></table>
<table>
<tr>
<td>
<textarea id='ChooseProduct' rows="5" cols="10">
TEST1
TEST2
TEST3
</textarea>
</td>
<td>
	<input type="button" id='btnRightAll' value='>>'/><br/>
	<input type="button" id='btnRight' value='>'/><br/>
	<input type="button" id='btnLeft'value='<' /><br/>
	<input type="button" id='btnLeftAll'value='<<' /><br/>
</td>
<td>
<textarea id='ProductList' rows="5" cols="10">
TEST1
TEST2
TEST3
</textarea>
</td>
</tr>
</table>

-->

<span id="spaMsg"></span>
<br />



