<?
echo $this->doctype(); 
	echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
	echo $this->headTitle('TOYOTA 南都汽車測驗系統')->setSeparator(' - ');
 echo $this->headLink()
		->appendStylesheet($this->baseUrl().'/css/site.css')
		->appendStylesheet($this->baseUrl().'/css/menu_style.css')
		->appendStylesheet($this->baseUrl().'/css/index.css')
		->appendStylesheet($this->baseUrl().'/css/index_layout.css')
		->appendStylesheet($this->baseUrl().'/css/'.$this->theme.'/jquery-ui.css')
		->appendStylesheet($this->baseUrl().'/css/'.$this->theme.'/jquery-ui-theme.css')
		->appendStylesheet($this->baseUrl().'/css/'.$this->theme.'/jquery-ui-min.css')
		->appendStylesheet($this->baseUrl().'/css/backstage.css')
		->appendStylesheet($this->baseUrl().'/css/treeview.css')	
		->appendStylesheet($this->baseUrl().'/css/datepicker.css')
		->appendStylesheet($this->baseUrl().'/css/ui.jqgrid.css');
		//->appendStylesheet($this->baseUrl().'/css/normalize.css'); //The dropdown-menu's width is incorrect!
?> 

<script src="<?echo $this->baseUrl();?>/js/jquery.menu.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery-ui.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery.easing.1.3.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/json2.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery.countdown.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery.gchart.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery.printElement.js" type="text/javascript"></script></head>

<script>var baseURL="<?echo $this->baseUrl();?>";</script>

<!-- Keep the http-equiv meta tag for IE8 -->
<meta http-equiv="X-UA-Compatible" content="IE=8" />
<!-- Start css3menu.com HEAD section -->
<link rel="stylesheet" href="index_layout.phtml_files/css3menu1/style.css" type="text/css" />
<!-- End css3menu.com HEAD section -->
</head>
<body class=<?echo STYLE;?>>
	<div class=<?echo STYLE;?> id='header1'>
		<img src="<?echo $this->baseUrl();?>/images/toyota.jpg"></div>
		<div class=<?echo STYLE;?> id='menu'>
			<ul>
				<li><a href=<?echo $this->baseUrl();?>>回首頁</a></li>
				<li><a href="<?echo $this->baseUrl();?>/default/index/about" title="關於南都">關於南都</a></li>
				<li><a onclick='$( "#content1" ).load( "login.html" );'title="測驗結果">測驗結果</a></li>
				<li><a href="<?echo $this->baseUrl();?>/default/index/description" title="測驗說明">測驗說明</a></li>
				<li><a href="<?echo $this->baseUrl();?>/auth/index" title="登入系統">登入測驗系統</a></li>
				<li><a href="<?echo $this->baseUrl();?>/auth/changepw" title="變更密碼">變更密碼</a></li>
			</ul>
		</div>
		
<?php echo $this->layout()->content; ?>

<div id='content1' class=<?echo STYLE;?> style="overflow-y:scroll; width:100%; height:400px;">
<h3>公司簡介</h3>
<br>一、創立日期：80年7月
<br>二、販賣區域及營業據點分佈：經營轄區包含雲林縣、嘉義縣(市)、台南縣(市)等五縣市，計有19個TOYOTA營業據點及2個LEXUS營業據點。
<br>三、名列天下、商週雜誌前100大服務業。
<br>四、轄區市場佔有率高達30%，成為消費者心目中最值得信賴的汽車公司。
<br>五、販賣體系的光榮佳績：榮獲TOYOTA全國夏季大競賽1997-2002年冠軍(締造六連霸紀錄)。榮獲TOYOTA全國保險大競賽1994-2004年冠軍(締造十一連霸紀錄)。
<br>六、服務體系的光榮佳績：榮獲TOYOTA全國技能競賽第六、八、十一屆冠軍。榮獲亞洲區小型車技能競賽1995、2002年冠軍。
<br>
<br>嘉義服務廠	嘉義市西區博愛路二段299號		(05)2330555
<br>南嘉義服務廠	嘉義市東區世賢路四段432號		(05)2231066
<br>民雄服務廠	嘉義縣民雄鄉民雄工業區中山路2-2號	(05)2219311
<br>朴子服務廠	嘉義縣朴子市大葛里大糠榔村1285號	(05)3706366
<br>斗南服務廠	雲林縣斗南鎮延平路二段87號		(05)5971191
<br>北港服務廠	雲林縣北港鎮華勝路356號			(05)7837833
<br>斗六服務廠	雲林縣斗六市大學路二段9號		(05)5346511
<br>崙背服務廠	雲林縣崙背鄉東明村南昌路533號		(05)6968566
<br>虎尾服務廠	雲林縣虎尾鎮頂南路300號			(05)6325811
<br>北台南服務廠	臺南市永康區中正南路214號		(06)2537866
<br>東台南服務廠	臺南市東區中華東路三段65號		(06)2697526
<br>新營服務廠	臺南市新營區民治路190號			(06)6565136
<br>西台南服務廠	臺南市中西區中華西路二段178號		(06)2989191
<br>佳里服務廠	臺南市佳里區民安里同安寮72之8號		(06)7233002
<br>歸仁服務廠	臺南市歸仁區中山路三段313號		(06)2395999
<br>永大服務廠	臺南市永康區永大路三段302號		(06)2014689
<br>官田服務廠	臺南市官田區南廓里南廓1-5號		(06)5793158
<br>善化服務廠	臺南市善化區興農路35號			(06)5818351
<br>安南服務廠	臺南市安南區海佃路2段155號		(06)2475968
   	            
	
</div>
	<div class=<?echo STYLE;?> align="center">南都汽車股份有限公司&copy;版權所有<br>710台南市永康區中正南路214號 電話：06-253-7866，建議使用IE瀏覽器1024X768</div>
<script src="<?echo $this->baseUrl();?>/js/timer.js" type="text/javascript"></script>

</body>
</html>
