<?php 
	echo $this->doctype(); 
	echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
	echo $this->headTitle('TOYOTA 南都汽車測驗系統')->setSeparator(' - ');
    echo $this->headLink()
		->appendStylesheet($this->baseUrl().'/css/site.css')
		->appendStylesheet($this->baseUrl().'/css/menu_style.css')
		->appendStylesheet($this->baseUrl().'/css/index.css')
		->appendStylesheet($this->baseUrl().'/css/index_layout.css')
		->appendStylesheet($this->baseUrl().'/css/jquery-ui.css')
		->appendStylesheet($this->baseUrl().'/css/backstage.css')
		->appendStylesheet($this->baseUrl().'/css/treeview.css')	
		->appendStylesheet($this->baseUrl().'/css/datepicker.css');
		//->appendStylesheet($this->baseUrl().'/css/normalize.css'); //The dropdown-menu's width is incorrect!
		
    	
?> 
<script src="<?echo $this->baseUrl();?>/js/jquery.menu.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery-ui.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery.easing.1.3.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/treeview.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/json2.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery.countdown.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/script.js" type="text/javascript"></script>

<script>var baseURL="<?echo $this->baseUrl();?>";</script>

<!-- Keep the http-equiv meta tag for IE8 -->
<meta http-equiv="X-UA-Compatible" content="IE=8" />
<!-- Start css3menu.com HEAD section -->
<link rel="stylesheet" href="index_layout.phtml_files/css3menu1/style.css" type="text/css" />
<!-- End css3menu.com HEAD section -->
</head>
<body class="auth_layout">
	<div id='header1'>
		<img src="<?echo $this->baseUrl();?>/images/toyota.jpg"></div>
		<div id='menu'>
			<ul>
				<li><a href="index.html" title="回首頁">回首頁</a></li>
				<li><a href="#" class="arrow no-click" title="關於南都">關於南都</a>
					<ul>
						<li><a href="#"  title="服務部">服務部</a></li>
						<li><a href="#" title="車輛部">車輛部</a></li>
						<li><a href="#" title="顧客關懷部">顧客關懷部</a></li>
						<li><a href="#" title="其他部門">其他部門</a></li>
					</ul>
				</li>
				<li><a onclick='$( "#content1" ).load( "login.html" );'title="我要報名">我要報名</a></li>
				<li><a onclick='$( "#content1" ).load( "login.html" );'title="測驗結果">測驗結果</a></li>
				<li><a onclick='$( "#content1" ).load( "help.html" );' title="測驗說明">測驗說明</a></li>
				<li><a href="<?echo $this->baseUrl();?>/auth/index" title="登入系統">登入測驗系統</a></li>
				<li><a href="<?echo $this->baseUrl();?>/auth/changepw" title="變更密碼">變更密碼</a></li>
			</ul>
		</div>
		
<?php echo $this->layout()->content; ?>

<div id='content1'>
			<table align="center">
					<td>
						<marquee onMouseOver="this.stop()" onMouseOut="this.start()"  width="400" height="20" direction=" right " scrolldelay="30" 
						scrollamount="3">南都測驗管理系統即將上線，敬請期待~
						</marquee>
					</td>
			</table>
			<fieldset>
				<legend>
				最新公告
				</legend>
						<td>
						test
						</td>
			</fieldset>
			
				<fieldset>
					<legend>
					榮譽榜
					</legend>
						<table  border=1 width=300>
								<td align=center>
									場別								
								</td>									
								<td align=center>
									員工編號
								</td>
									<tr>
								<td align=center>
									台南
								</td>
								<td align=center>
									123456789
								</td>
						</table>	
				</fieldset>
					
				
		</div>
	<div id='footer1' align="center">南都汽車股份有限公司&copy;版權所有<br>710台南市永康區中正南路214號 電話：06-253-7866，建議使用IE瀏覽器1024X768</div>
<script src="<?echo $this->baseUrl();?>/js/timer.js" type="text/javascript"></script>

</body>
</html>
