			<!-- Start css3menu.com BODY section -->
			<ul id="css3menu1" class="topmenu">
			<li class="topmenu"><a href="#" style="height:37px;line-height:37px;">
			<span><img src="/cca/public/images/menu/1.png" alt=""/><? echo FN_CAMPAIGN;?></span></a>
			<ul>
				<li class="subfirst"><a href="/cca/public/campaign/campaign/addcampaign"><? echo FN_ADD_CAMPAIGN;?></a></li>
				<li class="subfirst"><a href="/cca/public/campaign/campaign/updatecampaign"><? echo FN_UPDATE_CAMPAIGN;?></a></li>
				<li class="subfirst"><a href="/cca/public/campaign/campaign/deletecampaign"><? echo FN_DELETE_CAMPAIGN;?></a></li>
				<li class="subfirst"><a href="/cca/public/campaign/campaign/listcampaign"><? echo FN_LIST_CAMPAIGN;?></a></li>
				<li class="subfirst"><a href="/cca/public/campaign/campaign/groupcampaign"><? echo FN_GROUP_CAMPAIGN;?></a></li>
			</ul>
			</li>
			</ul>
			<!-- End css3menu.com BODY section -->
			<!-- Start css3menu.com BODY section -->
			<ul id="css3menu1" class="topmenu">
			<li class="topmenu"><a href="#" style="height:37px;line-height:37px;">
			<span><img src="/cca/public/images/menu/2.png" alt=""/><? echo FN_ENROLLMENT;?></span></a>
			<ul>
				<li class="subfirst"><a href="/cca/public/campaign/enrollment/addenrollment"><? echo FN_ADD_ENROLLMENT;?></a></li>
				<li class="subfirst"><a href="/cca/public/campaign/enrollment/updateenrollment"><? echo FN_UPDATE_ENROLLMENT;?></a></li>
				<li class="subfirst"><a href="/cca/public/campaign/enrollment/deleteenrollment"><? echo FN_DELETE_ENROLLMENT;?></a></li>
				<li class="subfirst"><a href="/cca/public/campaign/enrollment/listenrollment"><? echo FN_LIST_ENROLLMENT;?></a></li>
				<li class="subfirst"><a href="/cca/public/campaign/enrollment/groupenrollment"><? echo FN_GROUP_ENROLLMENT;?></a></li>
			</ul>
			</li>
			</ul>
			<!-- End css3menu.com BODY section -->
