<table name="main" style="width: 100%; height: 100%" border="1" cellpadding="0" cellspacing="0">
	<tr>
		<div name="banner" border=1 height="50" width="50">
			<td name="item1_1" colspan="3" style="width: 100%; height: 20%">
				Banner
			</td>
		</div>
	</tr>
	<tr>
		<div border=1 height="50" width="50">
			<td name="item2_1" style="width: 15%; height: 100%">
				<table name="leftmenu" style="width: 100%; height: 100%" border="1" cellpadding="0" cellspacing="0">
					<tr>
						<td name="login" style="width: 100%; height: 40%">
						Login
						</td>
					</tr>
					<tr>
						<td name="menu" style="width: 100%; height: 50%">
						Menu
						</td>
					</tr>
					<tr>
						<td name="status" style="width: 100%; height: 10%">
						Status
						</td>
					</tr>
				</table>
			</td>
		</div>
		<div border=1 height="50" width="50">
			<td name="item2_2" style="width: 70%; height: 100%">
				<table name="content" style="width: 100%; height: 100%" border="1" cellpadding="0" cellspacing="0">
					<tr>
						<td name="content" style="width: 100%; height: 100%">
						Content
						</td>
					</tr>
				</table>
			</td>
		</div>
		<div border=1 height="50" width="50">
			<td name="item2_3" style="width: 15%; height: 100%">
				<table name="rightinfo" style="width: 100%; height: 100%" border="1" cellpadding="0" cellspacing="0">
					<tr>
						<td name="info" style="width: 100%; height: 30%">
						Info
						</td>
					</tr>
					<tr>
						<td name="link" style="width: 100%; height: 70%">
						Link
						</td>
					</tr>
				</table>
			</td>
		</div>
	</tr>
	<tr>
		<div name="footer" border=1 height="50" width="50">
			<td name="item3_1" colspan="3" style="width: 100%; height: 10%">
				Footer
			</td>
		</div>
	</tr>
</table>
