<?
echo $this->doctype(); 
	echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
	echo $this->headTitle('TOYOTA 南都汽車測驗系統')->setSeparator(' - ');
 echo $this->headLink()
		->appendStylesheet($this->baseUrl().'/css/site.css')
		->appendStylesheet($this->baseUrl().'/css/menu_style.css')
		->appendStylesheet($this->baseUrl().'/css/index.css')
		->appendStylesheet($this->baseUrl().'/css/index_layout.css')
		->appendStylesheet($this->baseUrl().'/css/'.$this->theme.'/jquery-ui.css')
		->appendStylesheet($this->baseUrl().'/css/'.$this->theme.'/jquery-ui-theme.css')
		->appendStylesheet($this->baseUrl().'/css/'.$this->theme.'/jquery-ui-min.css')
		->appendStylesheet($this->baseUrl().'/css/backstage.css')
		->appendStylesheet($this->baseUrl().'/css/treeview.css')	
		->appendStylesheet($this->baseUrl().'/css/datepicker.css')
		->appendStylesheet($this->baseUrl().'/css/ui.jqgrid.css');
		//->appendStylesheet($this->baseUrl().'/css/normalize.css'); //The dropdown-menu's width is incorrect!
?> 

<script src="<?echo $this->baseUrl();?>/js/jquery.menu.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery-ui.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery.easing.1.3.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/json2.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery.countdown.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery.gchart.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery.printElement.js" type="text/javascript"></script>
</head>

<script>var baseURL="<?echo $this->baseUrl();?>";</script>

<!-- Keep the http-equiv meta tag for IE8 -->
<meta http-equiv="X-UA-Compatible" content="IE=8" />
<!-- Start css3menu.com HEAD section -->
<link rel="stylesheet" href="index_layout.phtml_files/css3menu1/style.css" type="text/css" />
<!-- End css3menu.com HEAD section -->
</head>
<body class=<?echo STYLE;?>>
	<div class=<?echo STYLE;?> id='header1'>
		<img src="<?echo $this->baseUrl();?>/images/toyota.jpg"></div>
		<div class=<?echo STYLE;?> id='menu'>
			<ul>
				<li><a href=<?echo $this->baseUrl();?>>回首頁</a></li>
				<li><a href="<?echo $this->baseUrl();?>/default/index/about" title="關於南都">關於南都</a></li>
				<li><a onclick='$( "#content1" ).load( "login.html" );'title="測驗結果">測驗結果</a></li>
				<li><a href="<?echo $this->baseUrl();?>/default/index/description" title="測驗說明">測驗說明</a></li>
				<li><a href="<?echo $this->baseUrl();?>/auth/index" title="登入系統">登入測驗系統</a></li>
				<li><a href="<?echo $this->baseUrl();?>/auth/changepw" title="變更密碼">變更密碼</a></li>
			</ul>
		</div>
		
<?php echo $this->layout()->content; ?>

<div class=<?echo STYLE;?> >
	<h3>1.測驗時記得攜帶員工證以便確認身分。</h3>
	<br>
	<h3>2.請注意測驗剩餘時間，在時間內作答。</h3>
	<br>
	<h3>3.測驗完畢後點選交卷按鈕，即可完成交卷，並結束作答。</h3>
	<br>
	<h3>4.可於左方攔位點選成績管理，查詢測驗成績。</h3>
</div>

	<div class=<?echo STYLE;?> align="center">南都汽車股份有限公司&copy;版權所有<br>710台南市永康區中正南路214號 電話：06-253-7866，建議使用IE瀏覽器1024X768</div>
<script src="<?echo $this->baseUrl();?>/js/timer.js" type="text/javascript"></script>

</body>
</html>
