<?echo $this->doctype();?>
<head>
<script>
var baseURL="<?echo $this->baseUrl();?>";
</script>
<?
echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
echo $this->headTitle('TOYOTA 南都汽車測驗系統')->setSeparator(' - ');
echo $this->headLink()
		->appendStylesheet($this->baseUrl().'/css/site.css')
		->appendStylesheet($this->baseUrl().'/css/menu_style.css')
		->appendStylesheet($this->baseUrl().'/css/index.css')
		->appendStylesheet($this->baseUrl().'/css/index_layout.css')
		->appendStylesheet($this->baseUrl().'/css/'.$this->theme.'/jquery-ui.css')
		->appendStylesheet($this->baseUrl().'/css/'.$this->theme.'/jquery-ui-theme.css')
		->appendStylesheet($this->baseUrl().'/css/'.$this->theme.'/jquery-ui-min.css')
		->appendStylesheet($this->baseUrl().'/css/backstage.css')
		->appendStylesheet($this->baseUrl().'/css/treeview.css')	
		->appendStylesheet($this->baseUrl().'/css/datepicker.css')
		->appendStylesheet($this->baseUrl().'/css/ui.jqgrid.css')
		->appendStylesheet($this->baseUrl().'/js/themes/default/easyui.css')
		->appendStylesheet($this->baseUrl().'/js/themes/icon.css')
		->appendStylesheet($this->baseUrl().'/css/jquery.autocomplete.css')
		->appendStylesheet($this->baseUrl().'/css/jqtree.css');
		
		//->appendStylesheet($this->baseUrl().'/css/normalize.css'); //The dropdown-menu's width is incorrect!
?> 

<script src="<?echo $this->baseUrl();?>/js/jquery.menu.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery-1.10.2.min.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery-ui.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery.easing.1.3.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/json2.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery.countdown.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery.gchart.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery-ui-timepicker-addon.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/jquery-ui-slide.min.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/tree.jquery.js" type="text/javascript"></script>
<!-- 
	Keep the http-equiv meta tag for IE8 
-->
<meta http-equiv="X-UA-Compatible" content="IE=8" />
<!-- 
	Start css3menu.com HEAD section 
-->
<link rel="stylesheet" href="index_layout.phtml_files/css3menu1/style.css" type="text/css" />
<!-- 
	End css3menu.com HEAD section 
-->
</head>
<body class="exam_layout <? echo STYLE;?> no-copy-paste" onload="openwin()">

<!-- 
	一定要放在此位置 
-->
<script src="<?echo $this->baseUrl();?>/js/script.js" type="text/javascript"></script>
<script src="<?echo $this->baseUrl();?>/js/treeview.js" type="text/javascript"></script>

<table class=<?echo STYLE;?> border= "0" name="main" style="width: 100%; height:460px;" border="0" cellpadding="0" cellspacing="0" >
<tr>

<!--
<td name="item1_1" colspan="2" style="width:100%; height:60px">
<img id="backlogo" src="<?//echo $this->baseUrl();?>/images/backend.jpg" height="100%" width="100%">
</td>

		<input id="browsefile" type="file" name="browsefile" style="margin-left:10px" class="database <?echo STYLE;?>" sql="upload" db="toyota" table="department,user" field="supervisor,name" key="department_id" style="display:none;">
		</input>

-->

<form id="browsefileform" name="browsefileform" action="<?//echo $this->baseUrl();?>/index/sql" method="post" enctype="multipart/form-data">
	<td name="item1_1" colspan="2" style="width:100%; height:60px">
		<img id="backlogo" src="<?echo $this->baseUrl();?>/images/backend.jpg" height="100%" width="100%"/>
	</td>
</form>

</tr>
<tr>
<td class=<?echo STYLE;?> name="item2_1" style="position:absolute; top:70px;width: 14%; height: 84%">
	<div id="leftmenu" class="<?echo STYLE;?>" style="width:100%;height:100%;float:left;">
		<ul class="container">
		<li class="menu">
		<ul>
			<li class="button"><a href="#" class="<?echo STYLE;?>">登入管理</a></li>
			<li class="dropdown">
		<ul>
			<li class="<?echo ACTIVE_STYLE;?>"><a href="<?echo $this->baseUrl();?>/index/index">回首頁</a></li>
			<li class="<?echo ACTIVE_STYLE;?>"><a href="<?echo $this->baseUrl();?>/exam/exam/account">帳號管理</a></li>			
			<li class="<?echo ACTIVE_STYLE;?>"><a href="<?echo $this->baseUrl();?>/exam/index/permissions">權限控管</a></li>
			<li class="<?echo ACTIVE_STYLE;?>"><a href="login.html">身分切換</a></li>
			<li class="<?echo ACTIVE_STYLE;?>"><a href="<?echo $this->baseUrl();?>/auth/changepw">變更密碼</a></li>
			<li class="<?echo ACTIVE_STYLE;?>"><a href="<?echo $this->baseUrl();?>/exam/index/home">MyTOYOTA</a></li>					
			<li class="<?echo ACTIVE_STYLE;?>"><a href="<?echo $this->baseUrl();?>/auth/logout">登出</a></li>					
		</ul>
			</li>
		</ul>
		<ul>
			<li class="button"><a href="#" class="<?echo STYLE;?>">考試管理</a></li>
			<li class="dropdown">
		<ul>
			<li class="<?echo ACTIVE_STYLE;?>"><a href="<?echo $this->baseUrl();?>/exam/exam/addexam">考試設定</a></li>
			<li class="<?echo ACTIVE_STYLE;?>"><a href="<?echo $this->baseUrl();?>/exam/exam/remainder">延長考試時間</a></li>		
			<li class="<?echo ACTIVE_STYLE;?>"><a href="<?echo $this->baseUrl();?>/exam/exam/monitor">監考管理</a></li>		
			<li class="<?echo ACTIVE_STYLE;?>"><a onclick='$( "#content" ).load( "userdata.html" );'>現場記錄保全</a></li>		
		</ul>
			</li>
		</ul>
		<ul>
			<li class="button"><a href="#" class="<?echo STYLE;?>">成績管理</a></li>
			<li class="dropdown">
		<ul>                    
			<li class="<?echo ACTIVE_STYLE;?>"><a href="<?echo $this->baseUrl();?>/exam/score/achievement">個人測驗成績</a></li>					
			<li class="<?echo ACTIVE_STYLE;?>"><a href="<?echo $this->baseUrl();?>/exam/score/radarchart">能力缺口檢測</a></li>
			<li class="<?echo ACTIVE_STYLE;?>"><a href="<?echo $this->baseUrl();?>/exam/score/inqueryscore">成績複查</a></li>
			<li class="<?echo ACTIVE_STYLE;?>"><a href="<?echo $this->baseUrl();?>/exam/score/portfolio">訓考歷程追蹤</a></li>
			<li class="<?echo ACTIVE_STYLE;?>"><a href="<?echo $this->baseUrl();?>/exam/score/statistic">成績統計分析</a></li>
			<li class="<?echo ACTIVE_STYLE;?>"><a href="<?echo $this->baseUrl();?>/exam/score/rank">榮譽排行榜</a></li>
		</ul>
			</li>
		</ul>
		<ul>
			<li class="button"><a href="#" class="<?echo STYLE;?>">模擬考試</a></li>
			<li class="dropdown">
			<ul>
				<li class="<?echo ACTIVE_STYLE;?>"><a href="<?echo $this->baseUrl();?>/exam/index/mock">模擬考</a></li>                   				
			</ul>
			</li>
			<li class="button"><a href="#" class="<?echo STYLE;?>">線上考試</a></li>
			<li class="dropdown">
			<ul>
				<li class="<?echo ACTIVE_STYLE;?>"><a href="<?echo $this->baseUrl();?>/exam/index/online">線上考試</a></li>                   				
			</ul>
			</li>
		</ul>
		<ul>
			<li class="button"><a href="#" class="<?echo STYLE;?>">個人資料</a></li>
			<li class="dropdown">
		<ul>
			<li class="<?echo ACTIVE_STYLE;?>"><a href="<?echo $this->baseUrl();?>/exam/user/groupuser">群組管理</a></li>
			<li class="<?echo ACTIVE_STYLE;?>"><a href="<?echo $this->baseUrl();?>/index/system">系統組態設定</a></li>
			<li class="<?echo ACTIVE_STYLE;?>"><a href="<?echo $this->baseUrl();?>/exam/user/listuser">使用者管理</a></li>		
		</ul>
			</li>
		</ul>
		<ul>
			<li class="button"><a href="#" class="<?echo STYLE;?>">公告管理</a></li>
			<li class="dropdown">
		<ul>
			<li class="<?echo ACTIVE_STYLE;?>"><a href="<?echo $this->baseUrl();?>/exam/post/latest">最新消息公布</a></li>
			<li class="<?echo ACTIVE_STYLE;?>"><a href="<?echo $this->baseUrl();?>/exam/post/welcome">歡迎頁面</a></li>
			<li class="<?echo ACTIVE_STYLE;?>"><a onclick='$( "#content" ).load( "bulletin.html" );'>自動通知管理</a></li>
			<li class="<?echo ACTIVE_STYLE;?>"><a href="<?echo $this->baseUrl();?>/exam/post/news">即時訊息發送</a></li>                   				
			
		</ul>
			</li>
		</ul>
		</li>
		</ul>
	</div>				
</td>
<td name="item2_2" style="width: 85%; height: 84%">
			<!-- 中間內容顯示位置 
			-->
<div class="<?echo STYLE;?>" style="padding-bottom: 85px; width: 99%; height: 100%;"> 
	<b>歡迎<?echo $this->user->user_id . $this->user->cname . 
		$this->user->role;?>，系統風格<?echo $this->theme?>，上次登入
		<?echo $this->user->logindate?></b>
	<b>您的即時訊息:</b>
	<?	echo $this->InstantMessage(); ?>
	<?php echo $this->layout()->content; ?>
</div>
</td>
</tr>
<tr style="height: 10%">
<td name="item3_1" colspan="3" style="width: 100%; height: auto">
<!-- 一定要放在此位置 
-->
<script src="<?echo $this->baseUrl();?>/js/timer.js" type="text/javascript"></script>
<div id="movable_footer" class=<?echo STYLE?> style="position: relative; margin-top: 14px;"  align="center"
title="崑山科大資訊管理系 洪俊銘博士團隊開發，專題製作產學合作案，連絡電話0935958365">
南都汽車股份有限公司&copy;版權所有. 710台南市永康區中正南路214號 電話：06-253-7866
</div>
</td>
</tr>
</table>
</body>
</html>
