			<!-- Start css3menu.com BODY section -->
			<ul id="css3menu1" class="topmenu">
			<li class="topmenu"><a href="#" style="height:37px;line-height:37px;">
			<span><img src="/cca/public/images/menu/1.png" alt=""/><? echo FN_USER;?></span></a>
			<ul>
				<li class="subfirst"><a href="/cca/public/system/user/adduser"><? echo FN_ADD_USER;?></a></li>
				<li class="subfirst"><a href="/cca/public/system/user/updateuser"><? echo FN_UPDATE_USER;?></a></li>
				<li class="subfirst"><a href="/cca/public/system/user/deleteuser"><? echo FN_DELETE_USER;?></a></li>
				<li class="subfirst"><a href="/cca/public/system/user/listuser"><? echo FN_LIST_USER;?></a></li>
				<li class="subfirst"><a href="/cca/public/system/user/groupuser"><? echo FN_GROUP_USER;?></a></li>
			</ul>
			</li>
			</ul>
			<!-- End css3menu.com BODY section -->
