<div class="pagination" style="width:100%">
    <div style="float:left;width:28%">
    </div>
    <div style="float:right;width:70%;">
        <!-- First page link -->
        <?php if (isset($this->previous)): ?>
              <a href="<?= $this->url(array('page' => $this->first)); ?>"><? echo VW_START;?></a> |
        <?php else: ?>
                <span class="disabled"><? echo VW_START;?></span> |
        <?php endif; ?>
    
        <!-- Previous page link -->
    
        <?php if (isset($this->previous)): ?>
              <a href="<?= $this->url(array('page' => $this->previous)); ?>">&lt; <? echo VW_PREVIOUS;?></a> |
        <?php else: ?>
            <span class="disabled">&lt; <? echo VW_PREVIOUS;?></span> |
        <?php endif; ?>
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a href="<?= $this->url(array('page' => $page)); ?>"><?= $page; ?></a>
            <?php else: ?>
                <?= $page; ?>
            <?php endif; ?>
        <?php endforeach; ?>
        <!-- Next page link -->

        <?php if (isset($this->next)): ?>
              | <a href="<?= $this->url(array('page' => $this->next)); ?>"><? echo VW_NEXT;?> &gt;</a> |
        <?php else: ?>
            | <span class="disabled"><? echo VW_NEXT;?> &gt;</span> |
        <?php endif; ?>
        <!-- Last page link -->
        <?php if (isset($this->next)): ?>
              <a href="<?= $this->url(array('page' => $this->last)); ?>"><? echo VW_END;?></a>
        <?php else: ?>
            <span class="disabled"><? echo VW_END;?></span>
        <?php endif; ?>
        &nbsp; <? echo VW_PAGE;?> <?= $this->current; ?> <? echo VW_OF;?> <?= $this->last; ?>
    </div>
</div>