<div id="welcome">
    <h2>MyKSU</h2>
	<h3>2013電信創新應用大賽將因應多螢趨勢與流行風潮，推出多項全新競賽項目，邀全民加入數位學習與創新研發。
中華電信董事長呂學錦表示，創新要有紮實的基本功，如全壘打王王貞治苦練的金雞獨立揮棒方式；或是iPhone、iPad，連2、3歲的小孩子也會玩。下一個憤怒鳥可遇不可求，但中華電信希望打造一個創新的環境，給年輕人去發揮。
</h3>

    <div id="more-information">
        <p><img src="/cca/public/images/logo.png" /></p>
        <p>
            <br />
            <a href="http://cca.ksu.edu.tw/">證照中心首頁</a> |
            <a href="http://www.hinet.net/innovation/">2013中華電信創新應用大賽</a>
        </p>
    </div>
</div>
